<a href="https://colab.research.google.com/github/cathrine36/numpy-/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [44]:
lst=[1,2,3,9,8,7]
arr=np.array(lst)
type(arr)
print(arr)

[1 2 3 9 8 7]


In [41]:
lst1=[1,2,3]
lst2=[9,7,6]
lst3=[3,4,5]
arr1=np.array([lst1,lst2,lst3])
print(arr1)

[[1 2 3]
 [9 7 6]
 [3 4 5]]


In [11]:
arr1.shape


(3, 3)

In [42]:
print(arr1)
arr1[:2,:1]

[[1 2 3]
 [9 7 6]
 [3 4 5]]


array([[1],
       [9]])

In [45]:
arr[4:]=100
print(arr)

[  1   2   3   9 100 100]


In [46]:
val=2
arr1[val<arr1]

array([3, 9, 7, 6, 3, 4, 5])

In [0]:
arr2=np.arange(0,6).reshape(2,3)
arr3=np.arange(0,6).reshape(2,3)
arr4=np.arange(0,6).reshape(2,3)

In [53]:
arr3*arr2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [54]:
sz=np.zeros((7,6),dtype = float)
sz

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
print(arr2)

[[0 1 2]
 [3 4 5]]


In [63]:
w=np.random.rand(2,20)
w

array([[0.03485119, 0.75613591, 0.35115054, 0.44144844, 0.20960641,
        0.58787202, 0.66432273, 0.14755201, 0.64702295, 0.56370848,
        0.24396486, 0.58515934, 0.37235857, 0.70310943, 0.26884586,
        0.04085326, 0.4239934 , 0.93903378, 0.20282361, 0.64651551],
       [0.57666268, 0.76984315, 0.67453654, 0.97610907, 0.46004431,
        0.74298317, 0.41495575, 0.96007615, 0.29945346, 0.00855721,
        0.81597975, 0.45676091, 0.47386928, 0.94426644, 0.75951792,
        0.8808204 , 0.07239072, 0.44627649, 0.83373473, 0.05177937]])